# Generated by Django 3.1.1 on 2021-05-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=20)),
                ('doj', models.DateField(max_length=20)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('timing', models.TextField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('meet_link', models.URLField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('patient_address', models.CharField(max_length=40)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='time_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=100)),
                ('from_time', models.CharField(max_length=10)),
                ('to_time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'time_slots',
            },
        ),
        migrations.CreateModel(
            name='Record_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_diagnoses', models.CharField(max_length=100)),
                ('medicines', models.CharField(max_length=100)),
                ('surgery', models.CharField(max_length=100)),
                ('other_details', models.CharField(max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitals.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crd_card_no', models.IntegerField()),
                ('dbt_card_no', models.IntegerField()),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_recv', models.IntegerField()),
                ('payment_bal', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.bills')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('dept', models.ManyToManyField(blank=True, to='hospitals.Department')),
                ('doctor', models.ManyToManyField(blank=True, to='hospitals.Doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.patient')),
            ],
        ),
    ]
